CREATE TABLE twitter.tweet (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  texto VARCHAR(255) DEFAULT NULL,
  idusuario INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;