CREATE TABLE twitter.tweetcomentarios (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  texto VARCHAR(255) DEFAULT NULL,
  idtweet INT(11) DEFAULT NULL,
  idusuario INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;