--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.470.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 15/01/2021 11:14:52
-- Server version: 10.4.17
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO twitter.tweet(id, texto, idusuario) VALUES
(1, 'Publicação 1', 1),
(2, 'Olá', 2);